### ISSUE TITLE
[Wiki] Issues with lang exampels

### ISSUE THREAD

**Issue by Xarmat-GitHub** [michelegargiulo/ThaumcraftAspectCreator#1]
**Custom Aspect Localization example don't work**

**This must be changed from:**
tc.aspect.electricae'=Electricity
tc.aspect.fulgur'=Lightning, Bolt
tc.aspect.tempestas'=Storm, Turbolence

**to**

tc.aspect.electricae=Electricity
tc.aspect.fulgur=Lightning, Bolt
tc.aspect.tempestas=Storm, Turbolence

Thanks for this great mod and your efforts.

**Comment by michelegargiulo** [comment]
Fixed! Thank you for reporting and for the good words. Have fun :)
